[tool.black]
line-length = 88

[tool.isort]
extra_standard_library = ["tomllib"]
line_length = 88
profile = "black"

[tool.pylint.main]
# A comma-separated list of package or module names from where C extensions may
# be loaded. Extensions are loading into the active Python interpreter and may
# run arbitrary code.
extension-pkg-allow-list = ["pygit2"]

# Pickle collected data for later comparisons.
persistent = false

[tool.pylint.format]
# Maximum number of characters on a single line.
max-line-length = 88

[tool.pylint.imports]
# Force import order to recognize a module as part of the standard compatibility
# libraries.
known-standard-library = ["tomllib"]

[tool.pylint."messages control"]
# Disable the message, report, category or checker with the given id(s). You can
# either give multiple identifiers separated by comma (,) or put this option
# multiple times (only on the command line, not in the configuration file where
# it should appear only once). You can also use "--disable=all" to disable
# everything first and then re-enable specific checks. For example, if you want
# to run only the similarities checker, you can use "--disable=all
# --enable=similarities". If you want to run only the classes checker, but have
# no Warning level messages displayed, use "--disable=all --enable=classes
# --disable=W".
disable = ["locally-disabled", "unknown-option-value"]

[tool.pylint.reports]
# Tells whether to display a full report or only the messages
reports = false

[tool.pylint.similarities]
# Minimum lines number of a similarity.
min-similarity-lines = 7
